version: '3.8'

services:
  # Symfony application (PHP + Nginx)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metricalo-app
    env_file:
      - .env
    tty: true
    volumes:
      - .:/var/www/html/metricalo
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"  # Map host port 8000 to container port 80
    depends_on:
      - database
    networks:
      - metricalo-network

  php:
    image: php:8.2-fpm
    container_name: metricalo-php
    volumes:
      - .:/var/www/html/metricalo
    networks:
      - metricalo-network

  # Composer service to install dependencies
  composer:
    image: composer:2.6
    container_name: composer
    volumes:
      - .:/var/www/html/metricalo
    working_dir: /var/www/html/metricalo
    command: ["composer", "install"]
    networks:
      - metricalo-network

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: metricalo-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - metricalo-network
###< doctrine/doctrine-bundle ###

networks:
  metricalo-network:
    name: metricalo-network

volumes:
  # db-data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
